import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-lista-alumnos',
  templateUrl: './lista-alumnos.component.html',
  styleUrls: ['./lista-alumnos.component.css'],
})
export class ListaAlumnosComponent implements OnInit {
  alumnosArray: any[] = [
    {
      nombre: 'Juan',
      apellido: 'Perez',
      edad: 20,
      curso: 'Angular',
      nota: 7,
      valoraciones: 3,
      beca: false,
    },
    {
      nombre: 'Pedro',
      apellido: 'Gonzalez',
      edad: 25,
      curso: 'Angular',
      nota: 9,
      valoraciones: 5,
      beca: true,
    },
    {
      nombre: 'Ana',
      apellido: 'Lopez',
      edad: 22,
      curso: 'Angular',
      nota: 8,
      valoraciones: 4,
      beca: true,
    },
    {
      nombre: 'Maria',
      apellido: 'Garcia',
      edad: 19,
      curso: 'Angular',
      nota: 6,
      valoraciones: 2,
      beca: false,
    },
    {
      nombre: 'Luis',
      apellido: 'Martinez',
      edad: 21,
      curso: 'Angular',
      nota: 10,
      valoraciones: 6,
      beca: true,
    },
    {
      nombre: 'Juana',
      apellido: 'Gomez',
      edad: 18,
      curso: 'Angular',
      nota: 5,
      valoraciones: 1,
      beca: true,
    },
    {
      nombre: 'Carlos',
      apellido: 'Rodriguez',
      edad: 23,
      curso: 'Angular',
      nota: 7,
      valoraciones: 3,
      beca: true,
    },
    {
      nombre: 'Daniel',
      apellido: 'Sanchez',
      edad: 24,
      curso: 'Angular',
      nota: 9,
      valoraciones: 5,
      beca: false,
    },
    {
      nombre: 'Antonio',
      apellido: 'Lopez',
      edad: 20,
      curso: 'Angular',
      nota: 8,
      valoraciones: 4,
      beca: true,
    },
    {
      nombre: 'Martha',
      apellido: 'Garcia',
      edad: 19,
      curso: 'Angular',
      nota: 6,
      valoraciones: 2,
      beca: true,
    },
    {
      nombre: 'Jorge',
      apellido: 'Martinez',
      edad: 21,
      curso: 'Angular',
      nota: 2,
      valoraciones: 6,
      beca: true,
    },
    {
      nombre: 'Julia',
      apellido: 'Gomez',
      edad: 18,
      curso: 'Angular',
      nota: 5,
      valoraciones: 1,
      beca: false,
    },
    {
      nombre: 'Carmen',
      apellido: 'Rodriguez',
      edad: 23,
      curso: 'Angular',
      nota: 7,
      valoraciones: 3,
      beca: false,
    },
    {
      nombre: 'David',
      apellido: 'Sanchez',
      edad: 24,
      curso: 'Angular',
      nota: 1,
      valoraciones: 5,
      beca: true,
    },
    {
      nombre: 'Juan',
      apellido: 'Lopez',
      edad: 20,
      curso: 'Angular',
      nota: 8,
      valoraciones: 4,
      beca: true,
    },
    {
      nombre: 'Martha',
      apellido: 'Garcia',
      edad: 19,
      curso: 'Angular',
      nota: 6,
      valoraciones: 2,
      beca: true,
    },
    {
      nombre: 'Jorge',
      apellido: 'Martinez',
      edad: 21,
      curso: 'Angular',
      nota: 10,
      valoraciones: 6,
      beca: true,
    },
    {
      nombre: 'Julia',
      apellido: 'Gomez',
      edad: 18,
      curso: 'Angular',
      nota: 5,
      valoraciones: 1,
      beca: true,
    },
    {
      nombre: 'Carmen',
      apellido: 'Rodriguez',
      edad: 23,
      curso: 'Angular',
      nota: 4,
      valoraciones: 3,
      beca: false,
    },
    {
      nombre: 'David',
      apellido: 'Sanchez',
      edad: 24,
      curso: 'Angular',
      nota: 9,
      valoraciones: 5,
      beca: true,
    },
    {
      nombre: 'Juan',
      apellido: 'Lopez',
      edad: 20,
      curso: 'Angular',
      nota: 8,
      valoraciones: 4,
      beca: true,
    },
    {
      nombre: 'Martha',
      apellido: 'Garcia',
      edad: 19,
      curso: 'Angular',
      nota: 6,
      valoraciones: 2,
      beca: true,
    },
    {
      nombre: 'Jorge',
      apellido: 'Martinez',
      edad: 21,
      curso: 'Angular',
      nota: 10,
      valoraciones: 6,
      beca: false,
    },
    {
      nombre: 'Julia',
      apellido: 'Gomez',
      edad: 18,
      curso: 'Angular',
      nota: 5,
      valoraciones: 1,
      beca: true,
    },
  ];

  alumnoNumero = 0;

  constructor() {}

  ngOnInit(): void {}

  sumarAlumno() {
    this.alumnoNumero++;
  }
}
